# Add source files here
EXECUTABLE	:= test_link_list
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= test_link_list.cpp

################################################################################
# Rules and targets

# NOTE: Assuming P4 based install until OpenCL becomes public
# Adjust P4_Root, default is ${HOME}/perforce/
# P4_ROOT=${HOME}/myperforce/

include ../../common/common_opencl.mk


